In [55]:
# Performing standard imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [56]:
ds = pd.read_csv('SMSSpamCollection',sep='\t',header=None)

In [57]:
ds.columns = ['Verdict','Message']

In [58]:
ds.head()

Verdict                                            Message
0     ham  Go until jurong point, crazy.. Available only ...
1     ham                      Ok lar... Joking wif u oni...
2    spam  Free entry in 2 a wkly comp to win FA Cup fina...
3     ham  U dun say so early hor... U c already then say...
4     ham  Nah I don't think he goes to usf, he lives aro...

In [59]:
X = ds['Message'].values

In [60]:
y = ds['Verdict'].values

In [61]:
from sklearn.feature_extraction.text import CountVectorizer

In [62]:
X = CountVectorizer().fit_transform(X).toarray()

In [63]:
X.shape

(5572, 8713)

In [93]:
from sklearn.feature_extraction.text import TfidfTransformer,TfidfVectorizer

In [65]:
X = TfidfTransformer().fit_transform(X).toarray()

In [66]:
from sklearn.model_selection import train_test_split

In [67]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [68]:
from sklearn.svm import SVC

In [75]:
classifier = SVC(kernel='linear')

In [76]:
classifier.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [77]:
y_pred = classifier.predict(X_test)

In [78]:
from sklearn.metrics import confusion_matrix

In [79]:
confusion_matrix(y_test,y_pred)

array([[1590,    3],
       [  18,  228]], dtype=int64)

In [83]:
from sklearn.naive_bayes import GaussianNB

In [84]:
confusion_matrix(y_pred, GaussianNB().fit(X_train,y_train).predict(X_test))

array([[1453,  155],
       [  15,  216]], dtype=int64)

In [85]:
from sklearn.ensemble import RandomForestClassifier

confusion_matrix(y_pred,RandomForestClassifier().fit(X_train,y_train).predict(X_test))

C:\Users\BibhuJha\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array([[1605,    3],
       [  34,  197]], dtype=int64)

In [86]:
from sklearn.linear_model import LogisticRegression

In [88]:
confusion_matrix(y_test,LogisticRegression().fit(X_train,y_train).predict(X_test))

C:\Users\BibhuJha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([[1591,    2],
       [  63,  183]], dtype=int64)

In [120]:
classifier = LogisticRegression()

In [119]:
from sklearn.pipeline import Pipeline

In [127]:
vectorized_classifier = Pipeline([('tfidf',TfidfVectorizer()),('clf',LogisticRegression())])

In [128]:
vectorized_classifier.fit(X_train)

AttributeError: 'numpy.ndarray' object has no attribute 'lower'